# mkdocs run
site_name: Software Development Project Documentation
nav:
  - 'index.md'
  - 'userguide.md'
  - 'Netcode Overview':
    - netcode/start.md
    - netcode/network_overview.md
    - netcode/TCP_connection.md
    - netcode/Packets.md
    - netcode/TCP_Transport_Layer.md
    - netcode/UDP_Transport_Layer.md
    - netcode/connection_packets.md
  - 'Networking':
    - 'networking/start.md'
    - 'networking/sending_a_packet.md'
    - 'networking/map_loading.md'
  - 'Server':
    - 'server/Player.md'
  - 'Client':
    - 'client/local_remote_player.md'
    - 'client/Game_Menus.md'
  - 'Weapon System':
    - 'weapons/weapons.md'
    - 'weapons/shooting.md'
    - 'weapons/weapon_switching.md'
    - 'weapons/damage_and_hitboxes.md'


  



theme:
    name: readthedocs
    include_homepage_in_sidebar: false
    highlightjs: true

